---
    # Location of the Protocol Database
    ProtocolDatabase: "../config/protocol_model_db.yaml"

    # Timeout in seconds after which a UDP flow will be considered to have ended
    UdpFlowTimeout: 120

    # Number of queues that are to be configured.
    # There is one thread per queue
    NumQueues: 2

    # The offset for the queue numbers. 
    # For example, 2 queues with an offset of 2000, would be queue 2000 and 2001
    QueueOffset: 0