---
    # Location of the Protocol Database
    ProtocolDatabase: "../config/protocol_model_db.yaml"

    # Timeout in seconds after which a UDP flow will be considered to have ended
    UdpFlowTimeout: 120

    # Number of queues that are to be configured.
    # There will be between 1 and NumWorkerThreadsPerQueue threads per queue
    NumQueues: 2

    # The offset for the queue numbers. 
    # For example, 2 queues with an offset of 2000, would be queue 2000 and 2001
    QueueOffset: 0

    # The size of the netfilter netlink userland queue
    NfQueueSize: 2048

    # The buffer size of to use for setting the Netfilter netlink queue
    # This is also the size of packets set as expected to receive from nfqueue
    NfBufSize: 2048

    # The KL Divergence Threshold. Any threshold below this will be considered that protocol
    KLDivergenceThreshold : 0.1

    # Number of worker threads to use in the Flow Manager. 
    # Each flow is assigned to a thread and that thread is responsible for all packets in the flow
    # The total number of threads used by the program will be NumQueues * NumWorkerThreadsPerQueue
    NumWorkerThreadsPerQueue: 10

    # Size of the thread packet queue to use for worker threads
    # If not using VerdictAfterClassification this should be larger than if using 
    WorkerThreadQueueSize: 4096

    # This controls whether the NfQueue verdict is set by the flow manager or the packet handler.
    # If true, the FlowManager / Flow will set the verdict. Which will be when it has processed the packet.
    #   This can allow drop packets if it fails to put the packet into the processing queue
    # If false, the packet is always set ot accept by the PacketHandler before passing control to the FlowManager
    VerdictAfterClassification: false

    # If the classification algorithm will look at protocols in the order of their port hints
    # when doing a classification. This may allow certain protocols to be preferred during
    # classification because they will be analysed first
    UsePortHints: true
