---
    # Location of the Protocol Database
    ProtocolDatabase: "../config/protocol_model_db.yaml"

    # Timeout in seconds after which a UDP flow will be considered to have ended
    UdpFlowTimeout: 120

    # Number of queues that are to be configured.
    # There is one thread per queue
    NumQueues: 3

    # The offset for the queue numbers. 
    # For example, 2 queues with an offset of 2000, would be queue 2000 and 2001
    QueueOffset: 0

    # The size of the netfilter netlink userland queue
    # Size is set using nfnl_rcvbufsiz and caluclated by NfQueueSize * NfBufSize
    NfQueueSize: 2048

    # The buffer size of to use for setting the Netfilter netlink queue
    # This is also the size of packets set as expected to receive from nfqueue
    NfBufSize: 2048

    # The KL Divergence Threshold. Any threshold below this will be considered that protocol
    KLDivergenceThreshold : 0.5

    # Number of worker threads to use in the Flow Manager. 
    # Each flow is assigned to a thread and that thread is responsible for all packets in the flow
    # The total number of threads used by the program will be NumQueues * NumWorkerThreadsPerQueue
    NumWorkerThreadsPerQueue: 2