---
    # Before this limit a protocol will not be considered matched.
    # This is used only in protocol matching and if set too high can stop protocols
    # with short packet bursts from being matched
    DefiningLimit: 10

    # After CutoffLimit number of packets no more packets will be processed.
    # This is for both protocol matching and algorithm training
    CutoffLimit: 500

    # Ordered List of Protocols
    # Once above the defining limit the list will use the port hints, then the order of this
    # limit in it's search for a protocol.
    # PortHints are also ordered by the order of this list
    ProtocolModels:
        - 
            # Name for the Protocol. 
            # Must be consistent and be the same used in training input
            ProtocolName: HTTP-Progressive

            # Number of flows used to generated this model
            FlowCount: 0

            # If it is enabled
            Enabled: true

            # The port hints that can be used in the order of searching
            # Currently not implemented
            PortHints:
                - 80
                - 8080

            AttributeMeters:
                -
                    # Name of the attribue meter. Must match those configured in program
                    AttributeName: DirectionBytesCountMeter  

                    # If the attribue meter is enabled for this protocol
                    Enabled: true

                    # Count of the number of flows in this meter
                    FlowCount: 0

                    # Ordered List representing the FingerPrint. 
                    # Number in sequence should be of the same as number of fingerprints
                    # e.g. 256 for byte frequencies
                    # 2 for % packet changes
                    FingerPrint: 
                        [
                            0,0
                        ]