 #!/bin/bash

src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http//http1.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http//http.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/https/https1.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/https/https_freyr_wlan.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_nginx_http_80_wifi_home_firefox1.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_nginx_http_80_wifi_home_firefox.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_http_8080__vlc_freyr_wlan_home_mp4_tbbt_s8e11.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_http_8080__vlc_freyr_wlan_home_mp4_tbbt_s8e12.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_http_8080__vlc_freyr_wlan_home_mp4_tbbt_s8e13.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_http_8080__vlc_freyr_wlan_home_mp4_tbbt_s8e18_2.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_http_8080__vlc_freyr_wlan_home_mp4_tbbt_s8e18.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_http_8080__vlc_freyr_wlan_home_mp4_tbbt_s8e19.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_http_8080__vlc_freyr_wlan_offaly_mp4_tbbt_s8e14.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_http_8080__vlc_freyr_wlan_offaly_mp4_tbbt_s8e15.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_http_8080__vlc_freyr_wlan_offaly_mp4_tbbt_s8e16.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_http_8080__vlc_freyr_wlan_offaly_mp4_tbbt_s8e17.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_nginx_http80_wifi_home_vlc_2.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_nginx_http80_wifi_home_vlc_3.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digitalocean_vlc_nginx_http80_wifi_home_vlc.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digiweb_http80_wifi_home_firefox_got_1.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/http_progressive//digiweb_http80_wifi_home_firefox_got_2.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtmp_cn_vlc_starstream_ch3q1_freyr_wifi.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtmp_nbc_sport_vlc_starstream_ch24q1_freyr_home_wifi1.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtmp_nbc_sport_vlc_starstream_ch24q1_freyr_home_wifi.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtmp_tsn_vlc_starstream_ch23q1_freyr_home_wifi1.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtmp_tsn_vlc_starstream_ch23q1_freyr_home_wifi2.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtmp_tsn_vlc_starstream_ch23q1_freyr_home_wifi3.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtmp_tsn_vlc_starstream_ch23q1_freyr_home_wifi4.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtmp_tsn_vlc_starstream_ch23q1_freyr_home_wifi.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtmp_villa_everton_vlc_starsream_ch23q1_freyr_home_wifi_poor_signal.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtmp_villa_mancity_vlc_starsream_ch24q1_freyr_home_wifi_closed_window.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//rtpm_starstream.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//starstream_ch14q1_ath_bca_wifi_dell_home.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//starstream_ch14q1_rom_udi_wifi_dell_home-1l.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtmp//starstream_ch14q1_rom_udi_wifi_dell_home-poorsignal.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/Youtube//youtube_flash_firefox.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/Youtube//youtube_html5_chrome.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/DNS//dns.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtsp_rtp//rtp_rtsp_digitalocean1.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtsp_rtp//rtp_rtsp_digitalocean2.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtsp_rtp//rtp_rtsp_digitalocean3.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtsp_rtp/rtsp_i_fullmetal_10.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtsp_rtp/rtsp_i_fullmetal_11.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtsp_rtp/rtsp_i_fullmetal_12.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtsp_rtp/rtsp_i_fullmetal_13.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtsp_rtp/rtsp_i_fullmetal_8.pcap
src/pcap_classifier/src/vsid_pcap_classifier -c ../config/config_pcap_classifier.yaml -p /media/matrim/toshiba/College/project/traces/rtsp_rtp/rtsp_i_fullmetal_9.pcap

